from __future__ import annotations

import json
import sqlite3
from collections.abc import Sequence
from pathlib import Path
from urllib.parse import urlparse

import click
from flask import current_app, g


SQLITE_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        email TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'operator',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_profiles (
        user_id INTEGER PRIMARY KEY,
        keywords TEXT NOT NULL DEFAULT '',
        sectors TEXT NOT NULL DEFAULT '',
        min_budget INTEGER NOT NULL DEFAULT 0,
        preferred_sources TEXT NOT NULL DEFAULT '',
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS source_policies (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        source_key TEXT UNIQUE NOT NULL,
        display_name TEXT NOT NULL,
        method TEXT NOT NULL,
        risk_level TEXT NOT NULL,
        frequency_minutes INTEGER NOT NULL,
        enabled INTEGER NOT NULL DEFAULT 1,
        config_json TEXT NOT NULL DEFAULT '{}',
        last_run_at TEXT,
        notes TEXT NOT NULL DEFAULT ''
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS opportunities (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        external_id TEXT,
        source_key TEXT NOT NULL,
        source_label TEXT NOT NULL,
        title TEXT NOT NULL,
        company TEXT NOT NULL DEFAULT '',
        url TEXT UNIQUE NOT NULL,
        budget_min INTEGER,
        budget_max INTEGER,
        budget_text TEXT NOT NULL DEFAULT '',
        currency TEXT NOT NULL DEFAULT 'USD',
        sector TEXT NOT NULL DEFAULT '',
        stack TEXT NOT NULL DEFAULT '[]',
        posted_at TEXT,
        risk_level TEXT NOT NULL DEFAULT 'low',
        risk_reasons TEXT NOT NULL DEFAULT '[]',
        score INTEGER NOT NULL DEFAULT 0,
        ai_summary TEXT NOT NULL DEFAULT '',
        suggested_reply TEXT NOT NULL DEFAULT '',
        analysis_json TEXT NOT NULL DEFAULT '{}',
        state TEXT NOT NULL DEFAULT 'NUEVO',
        is_suspicious INTEGER NOT NULL DEFAULT 0,
        raw_text TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_opportunities_state ON opportunities(state)",
    "CREATE INDEX IF NOT EXISTS idx_opportunities_score ON opportunities(score DESC)",
    "CREATE INDEX IF NOT EXISTS idx_opportunities_source ON opportunities(source_key)",
    """
    CREATE TABLE IF NOT EXISTS opportunity_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        opportunity_id INTEGER NOT NULL,
        actor_user_id INTEGER,
        event_type TEXT NOT NULL,
        previous_state TEXT,
        new_state TEXT,
        note TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE,
        FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS saved_views (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        query_string TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(user_id, name),
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS automation_runs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        trigger_kind TEXT NOT NULL,
        source_key TEXT NOT NULL,
        display_name TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL,
        fetched INTEGER NOT NULL DEFAULT 0,
        created INTEGER NOT NULL DEFAULT 0,
        updated INTEGER NOT NULL DEFAULT 0,
        skipped INTEGER NOT NULL DEFAULT 0,
        duration_ms INTEGER NOT NULL DEFAULT 0,
        error TEXT NOT NULL DEFAULT '',
        details_json TEXT NOT NULL DEFAULT '{}',
        started_at TEXT NOT NULL,
        finished_at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_automation_runs_started_at ON automation_runs(started_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_automation_runs_source_key ON automation_runs(source_key)",
)

POSTGRES_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'operator',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_profiles (
        user_id INTEGER PRIMARY KEY,
        keywords TEXT NOT NULL DEFAULT '',
        sectors TEXT NOT NULL DEFAULT '',
        min_budget INTEGER NOT NULL DEFAULT 0,
        preferred_sources TEXT NOT NULL DEFAULT '',
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS source_policies (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_key TEXT UNIQUE NOT NULL,
        display_name TEXT NOT NULL,
        method TEXT NOT NULL,
        risk_level TEXT NOT NULL,
        frequency_minutes INTEGER NOT NULL,
        enabled INTEGER NOT NULL DEFAULT 1,
        config_json TEXT NOT NULL DEFAULT '{}',
        last_run_at TEXT,
        notes TEXT NOT NULL DEFAULT ''
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS opportunities (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        external_id TEXT,
        source_key TEXT NOT NULL,
        source_label TEXT NOT NULL,
        title TEXT NOT NULL,
        company TEXT NOT NULL DEFAULT '',
        url TEXT UNIQUE NOT NULL,
        budget_min INTEGER,
        budget_max INTEGER,
        budget_text TEXT NOT NULL DEFAULT '',
        currency TEXT NOT NULL DEFAULT 'USD',
        sector TEXT NOT NULL DEFAULT '',
        stack TEXT NOT NULL DEFAULT '[]',
        posted_at TEXT,
        risk_level TEXT NOT NULL DEFAULT 'low',
        risk_reasons TEXT NOT NULL DEFAULT '[]',
        score INTEGER NOT NULL DEFAULT 0,
        ai_summary TEXT NOT NULL DEFAULT '',
        suggested_reply TEXT NOT NULL DEFAULT '',
        analysis_json TEXT NOT NULL DEFAULT '{}',
        state TEXT NOT NULL DEFAULT 'NUEVO',
        is_suspicious INTEGER NOT NULL DEFAULT 0,
        raw_text TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_opportunities_state ON opportunities(state)",
    "CREATE INDEX IF NOT EXISTS idx_opportunities_score ON opportunities(score DESC)",
    "CREATE INDEX IF NOT EXISTS idx_opportunities_source ON opportunities(source_key)",
    """
    CREATE TABLE IF NOT EXISTS opportunity_events (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        opportunity_id INTEGER NOT NULL,
        actor_user_id INTEGER,
        event_type TEXT NOT NULL,
        previous_state TEXT,
        new_state TEXT,
        note TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE,
        FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS saved_views (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        query_string TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
        UNIQUE(user_id, name),
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS automation_runs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trigger_kind TEXT NOT NULL,
        source_key TEXT NOT NULL,
        display_name TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL,
        fetched INTEGER NOT NULL DEFAULT 0,
        created INTEGER NOT NULL DEFAULT 0,
        updated INTEGER NOT NULL DEFAULT 0,
        skipped INTEGER NOT NULL DEFAULT 0,
        duration_ms INTEGER NOT NULL DEFAULT 0,
        error TEXT NOT NULL DEFAULT '',
        details_json TEXT NOT NULL DEFAULT '{}',
        started_at TEXT NOT NULL,
        finished_at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_automation_runs_started_at ON automation_runs(started_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_automation_runs_source_key ON automation_runs(source_key)",
)

DEFAULT_REDDIT_POLICY_CONFIG = {
    "urls": [
        "https://www.reddit.com/r/forhire/search.json?q=flair%3AHiring&restrict_sr=1&sort=new&limit=25",
        "https://www.reddit.com/r/freelance_forhire/search.json?q=hiring&restrict_sr=1&sort=new&limit=25",
    ],
    "search_terms": [
        "[hiring] python scraping",
        "[hiring] web scraping contract",
        "[hiring] n8n automation",
        "[hiring] api integration",
        "[hiring] backend automation",
        "[hiring] data engineer remote",
    ],
    "include_terms": [
        "python",
        "scraping",
        "automation",
        "n8n",
        "backend",
        "developer",
        "engineer",
        "software",
        "full stack",
        "full-stack",
        "api",
        "data",
        "etl",
    ],
    "exclude_terms": [
        "[for hire]",
        "for hire",
        "unpaid",
        "volunteer",
        "homework",
        "writer",
        "interviewer",
        "school",
        "minecraft",
        "telegram only",
        "whatsapp only",
    ],
    "max_items": 30,
}

DEFAULT_WORKANA_POLICY_CONFIG = {
    "search_urls": [
        "https://www.workana.com/es/jobs?category=it-programming&skills=python",
        "https://www.workana.com/es/jobs?category=it-programming&skills=web-scraping",
        "https://www.workana.com/es/jobs?category=it-programming&skills=automation",
        "https://www.workana.com/es/jobs?category=it-programming&skills=n8n",
    ],
    "include_terms": [],
    "exclude_terms": [
        "asistente virtual",
        "virtual assistant",
        "redaccion",
        "writer",
        "marketing",
        "ventas",
        "sales",
        "designer",
        "diseno grafico",
        "community manager",
    ],
    "candidate_limit": 24,
    "max_items": 24,
}

DEFAULT_GREENHOUSE_POLICY_CONFIG = {
    "boards": ["canonical", "vercel", "gitlab", "airtable", "netlify"],
    "include_terms": [
        "engineer",
        "developer",
        "backend",
        "back-end",
        "full stack",
        "full-stack",
        "python",
        "rust",
        "golang",
        "api",
        "platform",
        "data",
        "analytics",
        "automation",
        "integrat",
        "ai",
        "ml",
        "consultant",
        "contractor",
        "freelance",
    ],
    "exclude_terms": [
        "manager",
        "director",
        "head of",
        "sales",
        "account executive",
        "business development",
        "recruiter",
        "talent",
        "legal",
        "finance",
        "accountant",
        "marketing",
        "people partner",
        "support",
        "customer success",
    ],
    "remote_only": True,
    "max_items": 45,
}

DEFAULT_LEVER_POLICY_CONFIG = {
    "companies": ["applydigital"],
    "include_terms": [
        "engineer",
        "backend",
        "back-end",
        "developer",
        "consultant",
        "freelance",
        "martech",
        "automation",
        "solutions architect",
        "agentic",
        "qa",
    ],
    "exclude_terms": [
        "sales",
        "designer",
        "project manager",
        "scrum master",
        "marketing intern",
        "intern ",
        "engagement manager",
    ],
    "max_items": 20,
}

DEFAULT_WWR_POLICY_CONFIG = {
    "rss_urls": [
        "https://weworkremotely.com/categories/remote-back-end-programming-jobs.rss",
        "https://weworkremotely.com/categories/remote-programming-jobs.rss",
    ],
    "include_terms": [
        "engineer",
        "developer",
        "backend",
        "back-end",
        "full stack",
        "full-stack",
        "python",
        "automation",
        "integration",
        "data",
        "api",
        "software",
        "ai",
        "agent",
    ],
    "exclude_terms": [
        "frontend",
        "front-end",
        "design lead",
        "designer",
        "talent community",
        "firmware",
        "sales",
        "marketing",
        "customer success",
        "support",
        "recruiter",
        "wordpress",
        "shopware",
        "bubble",
    ],
    "max_items": 30,
}

DEFAULT_HN_JOBS_POLICY_CONFIG = {
    "endpoint": "https://hacker-news.firebaseio.com/v0/jobstories.json",
    "item_url_template": "https://hacker-news.firebaseio.com/v0/item/{id}.json",
    "candidate_limit": 60,
    "include_terms": [
        "engineer",
        "developer",
        "backend",
        "full stack",
        "full-stack",
        "python",
        "rust",
        "automation",
        "api",
        "data",
        "rails",
        "software",
        "ai",
        "ml",
    ],
    "exclude_terms": [
        "designer",
        "sales",
        "marketing",
        "recruiter",
        "customer success",
        "support",
        "intern",
    ],
    "max_items": 20,
}

DEFAULT_EMAIL_ALERTS_POLICY_CONFIG = {
    "min_score": 24,
    "max_age_days": 21,
}


DEFAULT_SOURCE_POLICIES = (
    {
        "source_key": "sample_feed",
        "display_name": "Demo Feed Local",
        "method": "fixture_json",
        "risk_level": "low",
        "frequency_minutes": 5,
        "enabled": 0,
        "config_json": "{}",
        "notes": "Fuente local de demostracion. Mantener deshabilitada en produccion real.",
    },
    {
        "source_key": "reddit",
        "display_name": "Reddit Public JSON",
        "method": "official_json_endpoints",
        "risk_level": "medium",
        "frequency_minutes": 30,
        "enabled": 1,
        "config_json": json.dumps(DEFAULT_REDDIT_POLICY_CONFIG, ensure_ascii=False),
        "notes": "Endpoints publicos JSON de Reddit orientados a freelance, automation, scraping y backend.",
    },
    {
        "source_key": "workana_projects",
        "display_name": "Workana Public Projects",
        "method": "public_project_pages",
        "risk_level": "low",
        "frequency_minutes": 90,
        "enabled": 1,
        "config_json": json.dumps(DEFAULT_WORKANA_POLICY_CONFIG, ensure_ascii=False),
        "notes": "Fuente freelance prioritaria: proyectos publicos de Workana con alta intencion de contratar por entregable u horas.",
    },
    {
        "source_key": "greenhouse",
        "display_name": "Greenhouse Public Boards",
        "method": "public_boards_api",
        "risk_level": "low",
        "frequency_minutes": 180,
        "enabled": 0,
        "config_json": json.dumps(DEFAULT_GREENHOUSE_POLICY_CONFIG, ensure_ascii=False),
        "notes": "Fuente secundaria: Greenhouse suele traer empleo formal y procesos ATS mas largos. Reactivala solo si quieres complementar con hiring corporativo.",
    },
    {
        "source_key": "lever",
        "display_name": "Lever Public Postings",
        "method": "public_postings_api",
        "risk_level": "low",
        "frequency_minutes": 180,
        "enabled": 0,
        "config_json": json.dumps(DEFAULT_LEVER_POLICY_CONFIG, ensure_ascii=False),
        "notes": "Fuente secundaria: Lever trae mas vacantes corporativas que proyectos freelance. Dejamos el conector disponible, pero apagado por default.",
    },
    {
        "source_key": "weworkremotely",
        "display_name": "We Work Remotely RSS",
        "method": "rss_feed",
        "risk_level": "low",
        "frequency_minutes": 120,
        "enabled": 1,
        "config_json": json.dumps(DEFAULT_WWR_POLICY_CONFIG, ensure_ascii=False),
        "notes": "Fuente publica RSS para remoto. Mantener polling conservador y filtros ligeros para no perder vacantes utiles.",
    },
    {
        "source_key": "hackernews_jobs",
        "display_name": "Hacker News Jobs",
        "method": "official_api",
        "risk_level": "low",
        "frequency_minutes": 180,
        "enabled": 0,
        "config_json": json.dumps(DEFAULT_HN_JOBS_POLICY_CONFIG, ensure_ascii=False),
        "notes": "Fuente secundaria: util para hiring tecnico, pero normalmente no es la mejor puerta de entrada para proyectos freelance rapidos.",
    },
    {
        "source_key": "public_pages",
        "display_name": "Paginas Publicas Compatibles",
        "method": "light_html_parse",
        "risk_level": "medium",
        "frequency_minutes": 180,
        "enabled": 0,
        "config_json": json.dumps({"urls": []}),
        "notes": "Configurar URLs compatibles con JSON: {\"urls\": [\"https://...\"]}.",
    },
    {
        "source_key": "email_alerts",
        "display_name": "Alertas por Correo",
        "method": "n8n_webhook_import",
        "risk_level": "low",
        "frequency_minutes": 60,
        "enabled": 0,
        "config_json": json.dumps(DEFAULT_EMAIL_ALERTS_POLICY_CONFIG, ensure_ascii=False),
        "notes": "Fuente recomendada para Upwork, Workana y otros marketplaces via n8n: captura alertas oficiales por correo y empujalas al import interno.",
    },
)


class Database:
    def __init__(self, connection, engine: str) -> None:
        self.connection = connection
        self.engine = engine

    def execute(self, query: str, params: Sequence | None = None):
        cursor = self.connection.cursor()
        cursor.execute(self._prepare_query(query), tuple(params or ()))
        return cursor

    def executescript(self, statements: Sequence[str]) -> None:
        cursor = self.connection.cursor()
        for statement in statements:
            cursor.execute(self._prepare_query(statement))

    def commit(self) -> None:
        self.connection.commit()

    def close(self) -> None:
        self.connection.close()

    def _prepare_query(self, query: str) -> str:
        if self.engine == "postgres":
            translated_parts: list[str] = []
            for character in query:
                if character == "?":
                    translated_parts.append("%s")
                elif character == "%":
                    translated_parts.append("%%")
                else:
                    translated_parts.append(character)
            return "".join(translated_parts)
        return query


def get_db() -> Database:
    if "db" not in g:
        database_url = current_app.config.get("DATABASE_URL")
        if database_url:
            g.db = _connect_postgres(database_url)
        else:
            database_path = Path(current_app.config["DATABASE"])
            g.db = _connect_sqlite(database_path)

    return g.db


def close_db(_error: Exception | None = None) -> None:
    connection = g.pop("db", None)
    if connection is not None:
        connection.close()


def bootstrap_database() -> None:
    db = get_db()
    schema_statements = POSTGRES_SCHEMA_STATEMENTS if db.engine == "postgres" else SQLITE_SCHEMA_STATEMENTS
    db.executescript(schema_statements)
    _ensure_runtime_columns(db)
    for policy in DEFAULT_SOURCE_POLICIES:
        db.execute(
            """
            INSERT INTO source_policies (
                source_key,
                display_name,
                method,
                risk_level,
                frequency_minutes,
                enabled,
                config_json,
                notes
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(source_key) DO NOTHING
            """,
            (
                policy["source_key"],
                policy["display_name"],
                policy["method"],
                policy["risk_level"],
                policy["frequency_minutes"],
                policy["enabled"],
                policy["config_json"],
                policy["notes"],
            ),
        )
    _refresh_source_policy_defaults(db)
    _cleanup_demo_data(db)
    db.commit()


def init_app(app) -> None:
    app.teardown_appcontext(close_db)

    @app.cli.command("init-db")
    def init_db_command() -> None:
        bootstrap_database()
        click.echo("Base de datos inicializada.")


def _connect_sqlite(database_path: Path) -> Database:
    database_path.parent.mkdir(parents=True, exist_ok=True)

    connection = sqlite3.connect(database_path)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON;")
    try:
        connection.execute("PRAGMA journal_mode = WAL;")
    except sqlite3.OperationalError:
        # Some restricted environments cannot update journal settings at all.
        pass
    try:
        connection.execute("PRAGMA synchronous = NORMAL;")
    except sqlite3.OperationalError:
        pass
    return Database(connection, engine="sqlite")


def _connect_postgres(database_url: str) -> Database:
    parsed = urlparse(database_url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        raise RuntimeError("DATABASE_URL must use a postgres:// or postgresql:// scheme.")

    try:
        from psycopg import connect
        from psycopg.rows import dict_row
    except ImportError as exc:
        raise RuntimeError(
            "psycopg is required for PostgreSQL support. Install dependencies from requirements.txt."
        ) from exc

    connection = connect(database_url, row_factory=dict_row)
    return Database(connection, engine="postgres")


def _refresh_source_policy_defaults(db: Database) -> None:
    rows = db.execute(
        """
        SELECT id, source_key, enabled, config_json, notes, frequency_minutes
        FROM source_policies
        """
    ).fetchall()

    is_production = current_app.config.get("ENVIRONMENT") == "production"
    demo_data = bool(current_app.config.get("DEMO_DATA"))

    db.execute(
        """
        UPDATE source_policies
        SET enabled = 1,
            frequency_minutes = 120,
            config_json = ?,
            notes = ?
        WHERE source_key = 'weworkremotely'
        """,
        (
            json.dumps(DEFAULT_WWR_POLICY_CONFIG, ensure_ascii=False),
            "Fuente publica RSS para remoto. Mantener polling conservador y filtros ligeros para no perder vacantes utiles.",
        ),
    )

    for row in rows:
        source_key = row["source_key"]
        config = _load_json(row["config_json"], default={})

        if demo_data:
            if source_key in {"sample_feed", "weworkremotely"}:
                db.execute(
                    """
                    UPDATE source_policies
                    SET enabled = 1,
                        frequency_minutes = ?,
                        config_json = ?,
                        notes = ?
                    WHERE id = ?
                    """,
                    (
                        5 if source_key == "sample_feed" else 120,
                        "{}"
                        if source_key == "sample_feed"
                        else json.dumps(DEFAULT_WWR_POLICY_CONFIG, ensure_ascii=False),
                        "Fuente local de demostracion. Activada para entornos locales de prueba."
                        if source_key == "sample_feed"
                        else "Fuente publica RSS para remoto. Mantener polling conservador y filtros ligeros para no perder vacantes utiles.",
                        row["id"],
                    ),
                )
            else:
                db.execute(
                    """
                    UPDATE source_policies
                    SET enabled = 0
                    WHERE id = ?
                    """,
                    (row["id"],),
                )
            continue

        if source_key == "sample_feed":
            if is_production and row["enabled"] == 1 and config == {}:
                db.execute(
                    "UPDATE source_policies SET enabled = 0, notes = ? WHERE id = ?",
                    ("Fuente local de demostracion. Mantener deshabilitada en produccion real.", row["id"]),
                )
            continue

        if source_key == "reddit" and is_production and (
            _is_blank_or_legacy_reddit_config(config) or _is_current_reddit_public_config(config)
        ):
            db.execute(
                """
                UPDATE source_policies
                SET enabled = 0,
                    frequency_minutes = 120,
                    config_json = ?,
                    notes = ?
                WHERE id = ?
                """,
                (
                    json.dumps(DEFAULT_REDDIT_POLICY_CONFIG, ensure_ascii=False),
                    "Deshabilitado en produccion Vercel: Reddit bloquea estos endpoints publicos. Reactivar manualmente solo si luego agregas una integracion autenticada.",
                    row["id"],
                ),
            )
            continue

        if source_key == "reddit" and _is_blank_or_legacy_reddit_config(config):
            db.execute(
                """
                UPDATE source_policies
                SET enabled = 1,
                    frequency_minutes = 30,
                    config_json = ?,
                    notes = ?
                WHERE id = ?
                """,
                (
                    json.dumps(DEFAULT_REDDIT_POLICY_CONFIG, ensure_ascii=False),
                    "Endpoints publicos JSON de Reddit orientados a freelance, automation, scraping y backend.",
                    row["id"],
                ),
            )
            continue

        if source_key == "workana_projects" and (
            _is_empty_collection_config(config, "search_urls")
            or _config_missing_terms(config, "exclude_terms", ("asistente virtual", "marketing", "sales"))
        ):
            db.execute(
                """
                UPDATE source_policies
                SET enabled = 1,
                    frequency_minutes = 90,
                    config_json = ?,
                    notes = ?
                WHERE id = ?
                """,
                (
                    json.dumps(DEFAULT_WORKANA_POLICY_CONFIG, ensure_ascii=False),
                    "Fuente freelance prioritaria: proyectos publicos de Workana con alta intencion de contratar por entregable u horas.",
                    row["id"],
                ),
            )
            continue

        if source_key == "greenhouse" and (
            _is_empty_collection_config(config, "boards")
            or _config_missing_terms(config, "exclude_terms", ("manager", "director", "head of"))
            or (
                _config_matches_default(config, DEFAULT_GREENHOUSE_POLICY_CONFIG)
                and row["notes"]
                == "Boards publicos de empresas remotas filtrados a roles de ingenieria, data y automatizacion."
            )
        ):
            db.execute(
                """
                UPDATE source_policies
                SET enabled = 0,
                    frequency_minutes = 180,
                    config_json = ?,
                    notes = ?
                WHERE id = ?
                """,
                (
                    json.dumps(DEFAULT_GREENHOUSE_POLICY_CONFIG, ensure_ascii=False),
                    "Fuente secundaria: Greenhouse suele traer empleo formal y procesos ATS mas largos. Reactivala solo si quieres complementar con hiring corporativo.",
                    row["id"],
                ),
            )
            continue

        if source_key == "lever" and (
            _is_empty_collection_config(config, "companies")
            or (
                _config_matches_default(config, DEFAULT_LEVER_POLICY_CONFIG)
                and row["notes"]
                == "Companies de Lever filtradas a roles tecnicos y freelance con mejor probabilidad de cierre rapido."
            )
        ):
            db.execute(
                """
                UPDATE source_policies
                SET enabled = 0,
                    frequency_minutes = 180,
                    config_json = ?,
                    notes = ?
                WHERE id = ?
                """,
                (
                    json.dumps(DEFAULT_LEVER_POLICY_CONFIG, ensure_ascii=False),
                    "Fuente secundaria: Lever trae mas vacantes corporativas que proyectos freelance. Dejamos el conector disponible, pero apagado por default.",
                    row["id"],
                ),
            )
            continue

        if source_key == "hackernews_jobs" and (
            _is_blank_or_missing_keys(
                config,
                "endpoint",
                "item_url_template",
            )
            or (
                _config_matches_default(config, DEFAULT_HN_JOBS_POLICY_CONFIG)
                and row["notes"]
                == "API oficial de Hacker News Jobs filtrada a roles tecnicos con URLs de aplicacion reales."
            )
        ):
            db.execute(
                """
                UPDATE source_policies
                SET enabled = 0,
                    frequency_minutes = 180,
                    config_json = ?,
                    notes = ?
                WHERE id = ?
                """,
                (
                    json.dumps(DEFAULT_HN_JOBS_POLICY_CONFIG, ensure_ascii=False),
                    "Fuente secundaria: util para hiring tecnico, pero normalmente no es la mejor puerta de entrada para proyectos freelance rapidos.",
                    row["id"],
                ),
            )
            continue

        if source_key == "email_alerts" and (
            _config_missing_keys(config, "min_score", "max_age_days")
            or (
                _config_matches_default(config, DEFAULT_EMAIL_ALERTS_POLICY_CONFIG)
                and row["notes"]
                == "Pensada para n8n: leer correo/IMAP o Gmail, normalizar vacantes y enviarlas al endpoint interno de importacion."
            )
        ):
            db.execute(
                """
                UPDATE source_policies
                SET enabled = 0,
                    frequency_minutes = 60,
                    config_json = ?,
                    notes = ?
                WHERE id = ?
                """,
                (
                    json.dumps(DEFAULT_EMAIL_ALERTS_POLICY_CONFIG, ensure_ascii=False),
                    "Fuente recomendada para Upwork, Workana y otros marketplaces via n8n: captura alertas oficiales por correo y empujalas al import interno.",
                    row["id"],
                ),
            )


def _cleanup_demo_data(db: Database) -> None:
    if current_app.config.get("ENVIRONMENT") != "production":
        return

    demo_rows = db.execute(
        "SELECT id FROM opportunities WHERE source_key = 'sample_feed' OR url LIKE 'https://sample.local/%'"
    ).fetchall()
    for row in demo_rows:
        db.execute("DELETE FROM opportunity_events WHERE opportunity_id = ?", (row["id"],))
    db.execute(
        "DELETE FROM opportunities WHERE source_key = 'sample_feed' OR url LIKE 'https://sample.local/%'"
    )


def _ensure_runtime_columns(db: Database) -> None:
    required_columns = {
        "opportunities": {
            "analysis_json": "TEXT NOT NULL DEFAULT '{}'",
        }
    }

    for table_name, columns in required_columns.items():
        existing = _get_table_columns(db, table_name)
        for column_name, column_definition in columns.items():
            if column_name in existing:
                continue
            db.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {column_definition}")

    db.commit()


def _get_table_columns(db: Database, table_name: str) -> set[str]:
    if db.engine == "sqlite":
        rows = db.execute(f"PRAGMA table_info({table_name})").fetchall()
        return {row["name"] for row in rows}

    rows = db.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = ?
        """,
        (table_name,),
    ).fetchall()
    return {row["column_name"] for row in rows}


def _load_json(raw_value: str, *, default):
    try:
        return json.loads(raw_value or "")
    except json.JSONDecodeError:
        return default


def _is_blank_or_legacy_reddit_config(config: dict) -> bool:
    if not config:
        return True

    urls = tuple(config.get("urls") or ())
    search_terms = tuple(config.get("search_terms") or ())
    legacy_urls = (
        "https://www.reddit.com/r/forhire/new/.json?limit=20",
        "https://www.reddit.com/r/freelance_forhire/new/.json?limit=20",
    )
    legacy_search_terms = (
        "python scraping freelance",
        "n8n automation contract",
        "rust backend freelance",
    )

    return urls == legacy_urls and search_terms == legacy_search_terms


def _is_current_reddit_public_config(config: dict) -> bool:
    if not config:
        return False

    urls = tuple(config.get("urls") or ())
    search_terms = tuple(config.get("search_terms") or ())
    return urls == tuple(DEFAULT_REDDIT_POLICY_CONFIG["urls"]) and search_terms == tuple(
        DEFAULT_REDDIT_POLICY_CONFIG["search_terms"]
    )


def _is_empty_collection_config(config: dict, key: str) -> bool:
    if not config:
        return True
    return not bool(config.get(key))


def _is_blank_or_missing_keys(config: dict, *keys: str) -> bool:
    if not config:
        return True
    return any(not config.get(key) for key in keys)


def _config_missing_terms(config: dict, key: str, terms: tuple[str, ...]) -> bool:
    if not config:
        return True
    values = {str(item).strip().lower() for item in config.get(key, []) if str(item).strip()}
    return any(term.lower() not in values for term in terms)


def _config_matches_default(config: dict, expected: dict) -> bool:
    return bool(config) and config == expected


def _config_missing_keys(config: dict, *keys: str) -> bool:
    if not config:
        return True
    return any(key not in config for key in keys)
